//
//  DirectoryData.swift
//  QAJF Barrington School Student Tool
//
//  Created by Jack Kamaryt on 4/19/23.
//

import Foundation

class DirectoryData {
    public static let shared = DirectoryData()
    
    func getData() -> [TeacherDataObject] {
        return [
            TeacherDataObject(name: "Steven Akin", title: "MTSS Data Entry Clerk", subject: "Support Personnel", email: "SAkin@barrington220.org"),
            TeacherDataObject(name: "Kelly Allen", title: "Certified Nursing Assistant Instructor", subject: "Science, Career & Technical Education", email: "KAllen@barrington220.org"),
            TeacherDataObject(name: "Janet Anderson", title: "Teacher Librarian", subject: "BHS Library Media Services", email: "JMAnderson@barrington220.org"),
            TeacherDataObject(name: "Michelle Anderson", title: "Teacher", subject: "Science", email: "MAnderson@barrington220.org"),
            TeacherDataObject(name: "Melanie Andrews", title: "Teacher", subject: "Mathematics", email: "MAndrews@barrington220.org"),
            TeacherDataObject(name: "John Ardente", title: "Horticulture Teacher", subject: "Science, Career & Technical Education", email: "JArdente@barrington220.org"),
            TeacherDataObject(name: "Kevin Art", title: "Interventionist", subject: "Wellness", email: "KArt@barrington220.org"),
            TeacherDataObject(name: "Roberto Avendano", title: "Spanish & French Teacher", subject: "BHS World Language", email: "RAvendano@barrington220.org"),
            TeacherDataObject(name: "Ally Badalamenti", title: "Teacher", subject: "Social Studies", email: "ABadalamenti@barrington220.org"),
            TeacherDataObject(name: "Robert M Baker", title: "Teacher", subject: "English", email: "RMBaker@barrington220.org"),
            TeacherDataObject(name: "Diana Barbarigos", title: "IEP Scheduling Coordinator", subject: "BHS Student Services & Support", email: "DBarbarigosRaedel@barrington220.org"),
            TeacherDataObject(name: "Barbara Barreiro", title: "Department Chair", subject: "Life Skills", email: "BBarreiro@barrington220.org"),
            TeacherDataObject(name: "Monica Barreiro", title: "Counselor", subject: "Counseling , BHS Counseling", email: "MBarreiro@barrington220.org"),
            TeacherDataObject(name: "Alexandra Bauer", title: "Interventionist", subject: "Wellness", email: "ABauer@barrington220.org"),
            TeacherDataObject(name: "Patricia Baumann", title: "Administrative Assistant", subject: "Social Studies", email: "Pbaumann@barrington220.org"),
            TeacherDataObject(name: "Julie Baylor", title: "Department Chair", subject: "Science", email: "JBaylor@barrington220.org"),
            TeacherDataObject(name: "Josh Beatty", title: "District Technology Support Specialist", subject: "Technology & Innovation", email: "JWBeatty@barrington220.org"),
            TeacherDataObject(name: "Julia Beatty", title: "Digital Photography Teacher", subject: "Career & Technical Education, BHS Fine, Visual & Performing Arts", email: "JBeatty@barrington220.org"),
            TeacherDataObject(name: "Mitchell Beck", title: "Department Chair", subject: "English", email: "MBeck@barrington220.org"),
            TeacherDataObject(name: "Laura Behnen", title: "Teacher", subject: "English", email: "LBehnen@barrington220.org"),
            TeacherDataObject(name: "Emily Behrendt", title: "Physical Education Teacher", subject: "Life Skills", email: "ebehrendt@barrington220.org"),
            TeacherDataObject(name: "William Bell", title: "Business Teacher", subject: "Social Studies , Career & Technical Education", email: "WBell@barrington220.org"),
            TeacherDataObject(name: "Mercedes Beltran", title: "Spanish Teacher & Multilingual Specialist", subject: "BHS World Language", email: "MBeltran@barrington220.org"),
            TeacherDataObject(name: "Jake Benz", title: "District Technology Support Technician", subject: "Technology & Innovation", email: "JBenz@barrington220.org"),
            TeacherDataObject(name: "Loretta Blecha", title: "Teacher", subject: "Mathematics", email: "LBlecha@barrington220.org"),
            TeacherDataObject(name: "Bonnie Bovard-Briggs", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "BBovardBriggs@barrington220.org"),
            TeacherDataObject(name: "Jack Bowyer", title: "Teacher", subject: "English", email: "JBowyer@barrington220.org"),
            TeacherDataObject(name: "Thomas Bredemeier", title: "Computer Science Teacher", subject: "Mathematics , Career & Technical Education", email: "TBredemeier@barrington220.org"),
            TeacherDataObject(name: "Jason Bryant", title: "Campus Technology Specialist", subject: "Safety & Security", email: "JBryant@barrington220.org"),
            TeacherDataObject(name: "Susan Buerckholtz", title: "Fine, Visual & Performing Arts Facilitator", subject: "Teaching & Learning, BHS Fine, Visual & Performing Arts", email: "SBuerckholtz@barrington220.org"),
            TeacherDataObject(name: "Neive Burger", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "NBurger@barrington220.org"),
            TeacherDataObject(name: "Jason Burke", title: "Ceramics Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "JDBurke@barrington220.org"),
            TeacherDataObject(name: "Laura Burke", title: "Administrative Asst. to Asst. Principal", subject: "BHS Main Office", email: "LLBurke@barrington220.org"),
            TeacherDataObject(name: "Marisabel Cajiao", title: "Bilingual Aide", subject: "BHS Student Services & Support", email: "MCajiao@barrington220.org"),
            TeacherDataObject(name: "Cristopher Calderon", title: "Skilled Maintenance Worker", subject: "Buildings & Grounds", email: "CCalderon@barrington220.org"),
            TeacherDataObject(name: "Sara Calhoun", title: "Teacher", subject: "Science", email: "SCalhoun@barrington220.org"),
            TeacherDataObject(name: "Melissa Campbell", title: "Vision Itinerant", subject: "", email: "MACampbell@barrington220.org"),
            TeacherDataObject(name: "Daniel Carnduff", title: "Teacher", subject: "Science", email: "DCarnduff@barrington220.org"),
            TeacherDataObject(name: "Cesar Carranza", title: "Spanish Teacher", subject: "BHS World Language", email: "CCarranza@barrington220.org"),
            TeacherDataObject(name: "Rudy Castaneda", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "RCastaneda@barrington220.org"),
            TeacherDataObject(name: "Kevin Chagoya Aguirre", title: "Groundsperson", subject: "Buildings & Grounds", email: "KChagoyaAguirre@barrington220.org"),
            TeacherDataObject(name: "Peter Chang", title: "Technology Support Technician", subject: "Technology & Innovation", email: "PChang@barrington220.org"),
            TeacherDataObject(name: "Erika Check", title: "Physics Teacher", subject: "Science", email: "EACheck@barrington220.org"),
            TeacherDataObject(name: "Emily Coklan", title: "Instructional Coach", subject: "Teaching & Learning", email: "ECoklan@barrington220.org"),
            TeacherDataObject(name: "Angela Concha", title: "Spanish Teacher", subject: "BHS World Language", email: "AConcha@barrington220.org" ),
            TeacherDataObject(name: "Christopher Condrad", title: "Latin Teacher", subject: "BHS World Language", email: "CCondrad@barrington220.org"),
            TeacherDataObject(name: "Douglas Connell", title: "Teacher", subject: "English", email: "DConnell@barrington220.org"),
            TeacherDataObject(name: "Marta Constenla", title: "Spanish Teacher", subject: "BHS World Language", email: "MConstenla@barrington220.org"),
            TeacherDataObject(name: "Brittany Cook", title: "Early Childhood Education Teacher", subject: "Life Skills, Career & Technical Education", email: "bcook@barrington220.org"),
            TeacherDataObject(name: "Corey Coots", title: "MTSS Coach", subject: "BHS Student Services & Support", email: "CCoots@barrington220.org"),
            TeacherDataObject(name: "Caleb Copeland", title: "Teacher", subject: "Science", email: "CCopeland@barrington220.org"),
            TeacherDataObject(name: "Deborah Cory", title: "Receptionist", subject: "BHS Main Office", email: "DCory@barrington220.org"),
            TeacherDataObject(name: "Michelle Cunningham", title: "Campus Attendant", subject: "Support Personnel", email: "MRCunningham@barrington220.org"),
            TeacherDataObject(name: "Anne Daehler", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "AMDaehler@barrington220.org"),
            TeacherDataObject(name: "Stephanie Daoud", title: "Administrative Asst. to Asst. Principal", subject: "BHS Main Office", email: "SDaoud@barrington220.org"),
            TeacherDataObject(name: "Madeline Dardanes", title: "Social Worker", subject: "BHS Student Services & Support", email: "MDardanes@barrington220.org"),
            TeacherDataObject(name: "Lauren Delehoy", title: "Culinary Arts Teacher", subject: "Life Skills, Career & Technical Education", email: "LDelehoy@barrington220.org"),
            TeacherDataObject(name: "Eric Delgado", title: "District Technology Support Associate", subject: "Technology & Innovation", email: "EDelgado@barrington220.org"),
            TeacherDataObject(name: "Brianne Delisi", title: "Psychologist", subject: "BHS Student Services & Support", email: "BDelisi@barrington220.org"),
            TeacherDataObject(name: "Marty Dello", title: "Driver's Education Teacher", subject: "Life Skills", email: "MDello@barrington220.org"),
            TeacherDataObject(name: "Shanna Dixon", title: "Teacher", subject: "Mathematics", email: "SDixon@barrington220.org"),
            TeacherDataObject(name: "Jeffrey Doles", title: "TV & Video Production Teacher", subject: "Career & Technical Education, BHS Fine, Visual & Performing Arts", email: "JDoles@barrington220.org"),
            TeacherDataObject(name: "Osman Donate", title: "Spanish & Multilingual Specialist", subject: "BHS World Language", email: "ODonate@barrington220.org"),
            TeacherDataObject(name: "Pablo Duenas", title: "Skilled Maintenance Worker", subject: "Buildings & Grounds", email: "PDuenas@barrington220.org"),
            TeacherDataObject(name: "Erica Duffy", title: "Assistant Director", subject: "Little Broncos", email: "EDuffy@barrington220.org"),
            TeacherDataObject(name: "Kathleen Duffy", title: "Teacher", subject: "Social Studies", email: "KADuffy@barrington220.org"),
            TeacherDataObject(name: "Shannon Dunn", title: "Behavior Intervention Specialist", subject: "BHS Student Services & Support", email: "SDunn@barrington220.org"),
            TeacherDataObject(name: "Lucia Dvorak", title: "Teacher", subject: "English", email: "LDvorak@barrington220.org"),
            TeacherDataObject(name: "Christopher Ebel", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "CEbel@barrington220.org"),
            TeacherDataObject(name: "Justin Edge", title: "District Technology Support Specialist", subject: "Technology & Innovation", email: "JEdge@barrington220.org"),
            TeacherDataObject(name: "Diana Emma", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "DEmma@barrington220.org"),
            TeacherDataObject(name: "Marla Engleman", title: "Counselor", subject: "Counseling , BHS Counseling", email: "MEngleman@barrington220.org"),
            TeacherDataObject(name: "Cameron Eugenis", title: "Lead Campus Attendant", subject: "Safety & Security", email: "CEugenis@barrington220.org"),
            TeacherDataObject(name: "Shannon Feineis", title: "Teacher", subject: "Science", email: "SFeineis@barrington220.org"),
            TeacherDataObject(name: "Elizabeth Felice", title: "Teacher", subject: "English", email: "EFelice@barrington220.org"),
            TeacherDataObject(name: "Vanessa Fennig", title: "Teacher", subject: "Science", email: "VFennig@barrington220.org"),
            TeacherDataObject(name: "Eduardo Fernandez", title: "Teacher", subject: "Social Studies", email: "EFernandez@barrington220.org"),
            TeacherDataObject(name: "Katherine Filosa", title: "Teacher", subject: "English", email: "KFilosa@barrington220.org"),
            TeacherDataObject(name: "Karen Fish", title: "Adapted PE Teacher", subject: "Student Services & Support", email: "KFish@barrington220.org"),
            TeacherDataObject(name: "Polly Foley", title: "Teacher", subject: "Science", email: "PFoley@barrington220.org"),
            TeacherDataObject(name: "Gretchen Friel", title: "Teacher", subject: "English", email: "GFriel@barrington220.org"),
            TeacherDataObject(name: "Sophie Frueh", title: "Nurse", subject: "BHS Health Office", email: "SFrueh@barrington220.org"),
            TeacherDataObject(name: "Derek Gablenz", title: "Teacher", subject: "Social Studies", email: "DGablenz@barrington220.org"),
            TeacherDataObject(name: "Eve Gaitan", title: "School Resource Officer", subject: "Safety & Security", email: "egaitan@barrington220.org"),
            TeacherDataObject(name: "Jolie Galovich", title: "Teacher", subject: "Science", email: "JGalovich@barrington220.org"),
            TeacherDataObject(name: "Carrie Galvan", title: "College Resource Center (CRC) Coordinator", subject: "Counseling , College Counseling", email: "CGalvan@barrington220.org"),
            TeacherDataObject(name: "Hilda Garcia", title: "Family School Liaison", subject: "BHS Student Services & Support", email: "HGarcia@barrington220.org"),
            TeacherDataObject(name: "Taylor Gaul", title: "Teacher", subject: "Mathematics", email: "TGaul@barrington220.org"),
            TeacherDataObject(name: "Matthew Gelon", title: "Teacher", subject: "Science", email: "MGelon@barrington220.org"),
            TeacherDataObject(name: "Michelle George", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "mgeorge1@barrington220.org"),
            TeacherDataObject(name: "Mary Georgeoff", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "MGeorgeoff@barrington220.org"),
            TeacherDataObject(name: "Kurt Gerlach", title: "Campus Attendant", subject: "Support Personnel", email: "KGerlach@barrington220.org"),
            TeacherDataObject(name: "Constandina Giannakopoulos", title: "English & ELL Teacher", subject: "English", email: "CGiannakopoulos@barrington220.org"),
            TeacherDataObject(name: "Erin Gibbons", title: "French Teacher", subject: "BHS World Language", email: "EKGibbons@barrington220.org"),
            TeacherDataObject(name: "Jon Gifford", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "JGifford@barrington220.org"),
            TeacherDataObject(name: "Alison Gildemeister", title: "Physical Education Teacher", subject: "Life Skills", email: "AGildemeister@barrington220.org"),
            TeacherDataObject(name: "Brett Glomp", title: "HVAC Technician", subject: "Buildings & Grounds", email: "BGlomp@barrington220.org"),
            TeacherDataObject(name: "Kimberly Golden", title: "Teacher", subject: "Mathematics", email: "KGolden@barrington220.org"),
            TeacherDataObject(name: "Sergio Gomez-Soto", title: "HVAC Technician", subject: "Buildings & Grounds", email: "SGomezSoto@barrington220.org"),
            TeacherDataObject(name: "David Gonzalez", title: "Director of Operations", subject: "District Administrative Center, Buildings & Grounds", email: "DGonzalez@barrington220.org"),
            TeacherDataObject(name: "Heather Graham", title: "Teacher", subject: "Mathematics", email: "HGraham@barrington220.org"),
            TeacherDataObject(name: "Alyssa Grewe", title: "Transition Facilitator", subject: "Student Services & Support", email: "AGrewe@barrington220.org"),
            TeacherDataObject(name: "Leslie Grider", title: "Hearing Itinerant", subject: "BHS Student Services & Support", email: "LGrider@barrington220.org"),
            TeacherDataObject(name: "Cynthia Guerrero", title: "Health Teacher", subject: "Life Skills, Career & Technical Education", email: "CGuerrero@barrington220.org"),
            TeacherDataObject(name: "Randall Gurnicz", title: "Groundsperson", subject: "Buildings & Grounds", email: "RGurnicz@barrington220.org"),
            TeacherDataObject(name: "Kyle Gutierrez", title: "District Driver", subject: "Buildings & Grounds", email: "KGutierrez@barrington220.org"),
            TeacherDataObject(name: "Gregory Hamann", title: "Work-Based Learning Teacher", subject: "Career & Technical Education, BHS Student Services & Support", email: "GHamann@barrington220.org"),
            TeacherDataObject(name: "Donald Hanson", title: "Groundsman", subject: "Buildings & Grounds", email: "DHanson@barrington220.org"),
            TeacherDataObject(name: "Stephanie Hargreaves", title: "Photography Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "SHargreaves@barrington220.org"),
            TeacherDataObject(name: "Christopher Hawkins", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "CHawkins@barrington220.org"),
            TeacherDataObject(name: "Stephanie Hawkins", title: "Teacher", subject: "Science", email: "SHawkins@barrington220.org"),
            TeacherDataObject(name: "Bree Heick", title: "Administrative Asst. to Associate Principal of Teaching and Learning", subject: "BHS Main Office", email: "BHeick@barrington220.org"),
            TeacherDataObject(name: "Sarah Heldt", title: "Teacher", subject: "English", email: "SHeldt@barrington220.org"),
            TeacherDataObject(name: "Nina Henning", title: "Day Care Assistant", subject: "Little Broncos", email: "NHenning@barrington220.org"),
            TeacherDataObject(name: "Lori Hermann", title: "Assistant Principal", subject: "BHS Main Office", email: "LHermann@barrington220.org"),
            TeacherDataObject(name: "Sean Higgins", title: "Psychologist", subject: "BHS Student Services & Support", email: "SHiggins@barrington220.org"),
            TeacherDataObject(name: "Caroline Hille", title: "Receptionist", subject: "Counseling , BHS Counseling", email: "CHille@barrington220.org"),
            TeacherDataObject(name: "Denise Hoffeller", title: "Administrative Asst. to Associate Principal of Student Services", subject: "BHS Main Office", email: "DHoffeller@barrington220.org"),
            TeacherDataObject(name: "Timothy Holman", title: "Foundations Program Teacher", subject: "BHS Student Services & Support", email: "THolman@barrington220.org"),
            TeacherDataObject(name: "Douglas Holtz", title: "Student Services Assistant", subject: "Student Services & Support", email: "DHoltz@barrington220.org"),
            TeacherDataObject(name: "Brenda Homola", title: "Director", subject: "Little Broncos", email: "BHomola@barrington220.org"),
            TeacherDataObject(name: "Cindy Honan", title: "Multilingual Specialist", subject: "BHS World Language", email: "CHonan@barrington220.org"),
            TeacherDataObject(name: "Tim Honor", title: "", subject: "", email: "THonor@barrington220.org"),
            TeacherDataObject(name: "Lisa Horcher", title: "Community Connections Coordinator", subject: "Counseling , BHS Counseling", email: "LHorcher@barrington220.org"),
            TeacherDataObject(name: "Kenneth Hoving", title: "Department Chair", subject: "BHS Student Services & Support", email: "KHoving@barrington220.org"),
            TeacherDataObject(name: "Meghan Hoxmeier", title: "Teacher", subject: "Mathematics", email: "MHoxmeier@barrington220.org"),
            TeacherDataObject(name: "Margarita Ianeva", title: "Title I In-School Student Support", subject: "", email: "MIaneva@barrington220.org"),
            TeacherDataObject(name: "Ninja Idrizi", title: "Associate Principal of Teaching and Learning", subject: "Life Skills, Career & Technical Education, BHS Main Office", email: "NIdrizi@barrington220.org"),
            TeacherDataObject(name: "Michelle Jakubowski", title: "Academic Support Teacher", subject: "Mathematics", email: "MJakubowski@barrington220.org"),
            TeacherDataObject(name: "Kristin Janowiak", title: "Teacher", subject: "Mathematics", email: "KJanowiak@barrington220.org"),
            TeacherDataObject(name: "Robert Jensen", title: "District Technology Support Technician", subject: "District Administrative Center, Technology & Innovation", email: "RJensen@barrington220.org"),
            TeacherDataObject(name: "Amy Jessup-Tilford", title: "Auditorium Director", subject: "BHS Fine, Visual & Performing Arts", email: "ATilford-Jessup@barrington220.org"),
            TeacherDataObject(name: "Austin Johnson", title: "Director of Safety & Security", subject: "District Administrative Center, Safety & Security", email: "AJohnson@barrington220.org"),
            TeacherDataObject(name: "Lucas Johnson", title: "Teacher", subject: "Mathematics", email: "LJohnson@barrington220.org"),
            TeacherDataObject(name: "Rachel Johnson", title: "Aqua Aide", subject: "Life Skills", email: "RMJohnson@barrington220.org"),
            TeacherDataObject(name: "Loretta Jones", title: "District Cataloguer", subject: "BHS Library Media Services", email: "LAJones@barrington220.org"),
            TeacherDataObject(name: "Troy Jones", title: "District Technology Support Technician", subject: "District Administrative Center, Technology & Innovation", email: "TJones@barrington220.org"),
            TeacherDataObject(name: "Dana Joyce", title: "Counselor", subject: "Counseling , BHS Counseling", email: "djoyce@barrington220.org"),
            TeacherDataObject(name: "Daniel Jung", title: "Electrician", subject: "Buildings & Grounds", email: "DJung@barrington220.org"),
            TeacherDataObject(name: "Jason Kaiser", title: "Woodworking Teacher", subject: "Career & Technical Education, BHS Fine, Visual & Performing Arts", email: "JKaiser@barrington220.org"),
            TeacherDataObject(name: "Randy Karon", title: "Band Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "Rkaron@barrington220.org"),
            TeacherDataObject(name: "Anna Kaszuba", title: "Teacher", subject: "English", email: "AKaszuba@barrington220.org"),
            TeacherDataObject(name: "Michael Kedzie", title: "Environmental Science Teacher", subject: "Science, Career & Technical Education", email: "MKedzie@barrington220.org"),
            TeacherDataObject(name: "Susan Kienzle", title: "Teacher", subject: "English", email: "SKienzle@barrington220.org"),
            TeacherDataObject(name: "Hal Kline", title: "Social Worker", subject: "Student Services & Support", email: "HKline@barrington220.org"),
            TeacherDataObject(name: "Karen Koeppel", title: "Testing Center Supervisor", subject: "Support Personnel", email: "KKoeppel@barrington220.org"),
            TeacherDataObject(name: "Marcey Kolb", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "mkolb@barrington220.org"),
            TeacherDataObject(name: "Lance Kopera", title: "Campus Attendant", subject: "Support Personnel", email: "LKopera@barrington220.org"),
            TeacherDataObject(name: "Elizabeth Kotrba", title: "Culinary Arts Teacher", subject: "Life Skills, Career & Technical Education", email: "ekotrba@barrington220.org"),
            TeacherDataObject(name: "Eric Kublank", title: "Skilled Maintenance Worker", subject: "Buildings & Grounds", email: "EKublank@barrington220.org"),
            TeacherDataObject(name: "J Eric Kuffel", title: "Business & Finance Teacher", subject: "Social Studies , Career & Technical Education", email: "EKuffel@barrington220.org"),
            TeacherDataObject(name: "Marcus Kuiper", title: "Physical Education Teacher", subject: "Life Skills", email: "MKuiper@barrington220.org"),
            TeacherDataObject(name: "Todd Kuklinski", title: "Teacher", subject: "Social Studies", email: "TKuklinski@barrington220.org"),
            TeacherDataObject(name: "Bridget Lacson", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "BLacson@barrington220.org"),
            TeacherDataObject(name: "Ernest Lane", title: "Teacher", subject: "Mathematics", email: "ELane@barrington220.org"),
            TeacherDataObject(name: "Tyler Lawson", title: "Teacher", subject: "English", email: "TLawson@barrington220.org"),
            TeacherDataObject(name: "Nicholas Lazar", title: "Teacher", subject: "Science", email: "NLazar@barrington220.org"),
            TeacherDataObject(name: "Deborah LeComte", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "DLeComte@barrington220.org"),
            TeacherDataObject(name: "Nona Leidig-Arnold", title: "Administrative Assistant", subject: "Buildings & Grounds", email: "NLeidigArnold@barrington220.org"),
            TeacherDataObject(name: "Lisa Lent", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "LLent@barrington220.org"),
            TeacherDataObject(name: "Paula Levin", title: "Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "plevin@barrington220.org"),
            TeacherDataObject(name: "Kristen Lewis", title: "Computer Science Teacher", subject: "Mathematics , Career & Technical Education", email: "KLewis@barrington220.org"),
            TeacherDataObject(name: "Robert Lewis", title: "Build 220 Project Coordinator", subject: "District Administrative Center, Buildings & Grounds", email: "RLewis@barrington220.org"),
            TeacherDataObject(name: "Stacey Lidbury", title: "Registrar", subject: "BHS Main Office", email: "SLidbury@barrington220.org"),
            TeacherDataObject(name: "Laurie Lindquist", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "LLindquist@barrington220.org"),
            TeacherDataObject(name: "Erin Lindsey", title: "Teacher", subject: "Science", email: "ELindsey@barrington220.org"),
            TeacherDataObject(name: "Eloy Llamas", title: "Groundsman", subject: "Buildings & Grounds", email: "ELlamas@barrington220.org"),
            TeacherDataObject(name: "Ann Marie Locke", title: "Nurse", subject: "BHS Health Office", email: "ALocke@barrington220.org"),
            TeacherDataObject(name: "Jorge Lopez", title: "Maintenance Worker", subject: "Buildings & Grounds", email: "JLopez7@barrington220.org"),
            TeacherDataObject(name: "Linda Lopez", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "LMLopez@barrington220.org"),
            TeacherDataObject(name: "Amy Lovi", title: "Teacher", subject: "English", email: "ALovi@barrington220.org"),
            TeacherDataObject(name: "Jodi Maasarani", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "JMaasarani@barrington220.org"),
            TeacherDataObject(name: "Beth MacDuff", title: "Teacher", subject: "Mathematics", email: "BMacDuff@barrington220.org"),
            TeacherDataObject(name: "Holly Majerchin", title: "Health Office Clerk", subject: "BHS Health Office", email: "HMajerchin@barrington220.org"),
            TeacherDataObject(name: "Kevin Majerchin", title: "Campus Attendant", subject: "Support Personnel", email: "KMajerchin@barrington220.org"),
            TeacherDataObject(name: "Alexis Mangiardi", title: "Teacher", subject: "Mathematics", email: "AMangiardi@barrington220.org"),
            TeacherDataObject(name: "Mark Markwell", title: "Aqua Aide", subject: "Life Skills", email: "Mmarkwell@barrington220.org"),
            TeacherDataObject(name: "Timothy Martin", title: "Counselor", subject: "Counseling , BHS Counseling", email: "TMartin@barrington220.org"),
            TeacherDataObject(name: "Raul Martinez Flores", title: "Groundsman", subject: "Buildings & Grounds", email: "RMartinezFlores@barrington220.org"),
            TeacherDataObject(name: "Casandra May", title: "Activities Account Clerk", subject: "Support Personnel", email: "CMMay@barrington220.org"),
            TeacherDataObject(name: "Kathie McCroary", title: "Nurse", subject: "BHS Health Office", email: "KMcCroary@barrington220.org"),
            TeacherDataObject(name: "Heath McFaul", title: "Associate Principal of Student Services", subject: "BHS Main Office", email: "HMcFaul@barrington220.org"),
            TeacherDataObject(name: "Jeffrey McMahon", title: "Environmental Science Teacher", subject: "Science, Career & Technical Education", email: "JMcMahon@barrington220.org"),
            TeacherDataObject(name: "Colleen McNiff", title: "Foundations Program Teacher", subject: "BHS Student Services & Support", email: "cmcniff@barrington220.org"),
            TeacherDataObject(name: "Stephen McWilliams", title: "Principal/Asst. Superintendent for Operations", subject: "BHS Main Office, Administration", email: "SMcWilliams@barrington220.org"),
            TeacherDataObject(name: "Matthew Medansky", title: "Teacher", subject: "Mathematics", email: "MMedansky@barrington220.org"),
            TeacherDataObject(name: "Madeline Meehan", title: "Speech Language Pathologist", subject: "BHS Student Services & Support", email: "MKMeehan@barrington220.org"),
            TeacherDataObject(name: "Michael Meister", title: "Campus Attendant", subject: "Support Personnel", email: "MMeister@barrington220.org"),
            TeacherDataObject(name: "Andres Mena Beltran", title: "Groundsman", subject: "Buildings & Grounds", email: "AMena@barrington220.org"),
            TeacherDataObject(name: "Jana Mendro", title: "Teacher", subject: "Mathematics", email: "JMendro@barrington220.org"),
            TeacherDataObject(name: "Jonathan Mihevc", title: "Teacher", subject: "English", email: "JMihevc@barrington220.org"),
            TeacherDataObject(name: "Alex Mikolajewski", title: "Physical Education Teacher", subject: "Life Skills", email: "AMikolajewski@barrington220.org"),
            TeacherDataObject(name: "Rachael Miller", title: "Speech Language Pathologist", subject: "Student Services & Support", email: "ramiller@barrington220.org"),
            TeacherDataObject(name: "Caroline Milne", title: "Teacher", subject: "Science", email: "CMilne@barrington220.org"),
            TeacherDataObject(name: "Laura Minerva", title: "Journalism Teacher", subject: "English, Career & Technical Education", email: "LMinerva@barrington220.org"),
            TeacherDataObject(name: "Joseph Molloy", title: "Interventionist", subject: "Wellness", email: "JMolloy@barrington220.org"),
            TeacherDataObject(name: "Kathleen Moody", title: "Post High School Counselor", subject: "Counseling , College Counseling", email: "KMoody@barrington220.org"),
            TeacherDataObject(name: "Sophia Moraris", title: "Teacher", subject: "Mathematics", email: "SMoraris@barrington220.org"),
            TeacherDataObject(name: "Tessa Mulvaney", title: "Photojournalism Teacher", subject: "English, Career & Technical Education", email: "TMulvaney@barrington220.org"),
            TeacherDataObject(name: "Lisa Nardiello", title: "Spanish Teacher", subject: "BHS World Language", email: "LNardiello@barrington220.org"),
            TeacherDataObject(name: "Stephanie Naumowicz", title: "Teacher", subject: "Life Skills, English", email: "SNaumowicz@barrington220.org"),
            TeacherDataObject(name: "Michele Neumann", title: "Campus Attendant", subject: "Support Personnel", email: "MNeumann@barrington220.org"),
            TeacherDataObject(name: "Heather Nevers", title: "Attendance Data Processor", subject: "Support Personnel", email: "HNevers@barrington220.org"),
            TeacherDataObject(name: "Nathan Newhalfen", title: "Teacher", subject: "Social Studies", email: "NNewhalfen@barrington220.org"),
            TeacherDataObject(name: "Tracy Nightingale", title: "Attendance Data Processor", subject: "Support Personnel", email: "TNightingale@barrington220.org"),
            TeacherDataObject(name: "Allen Noland", title: "Business Teacher", subject: "Social Studies , Career & Technical Education", email: "ANoland@barrington220.org"),
            TeacherDataObject(name: "Susan Oakley", title: "Administrative Assistant to Coordinator of Secondary Counseling", subject: "BHS Main Office, BHS Counseling", email: "SOakley@barrington220.org"),
            TeacherDataObject(name: "Timothy OConnor", title: "Teacher", subject: "Social Studies", email: "TOConnor@barrington220.org"),
            TeacherDataObject(name: "Ryan Palmer", title: "Teacher", subject: "Mathematics", email: "RPalmer@barrington220.org"),
            TeacherDataObject(name: "Lilia Pantoja", title: "Bilingual Assistant", subject: "Counseling , BHS Counseling", email: "LPantoja@barrington220.org"),
            TeacherDataObject(name: "Jane Papadimitriou", title: "Student Services Assistant", subject: "Student Services & Support", email: "JPapadimitriou@barrington220.org"),
            TeacherDataObject(name: "Karuna Parmar", title: "Architecture & Engineering Teacher", subject: "Science, Career & Technical Education", email: "KParmar@barrington220.org"),
            TeacherDataObject(name: "John Parolin", title: "Teacher", subject: "Social Studies", email: "JParolin@barrington220.org"),
            TeacherDataObject(name: "Lisa Parrilli", title: "Computer Science Teacher", subject: "Mathematics , Career & Technical Education", email: "LParrilli@barrington220.org"),
            TeacherDataObject(name: "Florence Pastin", title: "Administrative Assistant", subject: "BHS World Language", email: "Fpastin@barrington220.org"),
            TeacherDataObject(name: "Mara Pearson", title: "Administrative Assistant", subject: "BHS Student Services & Support", email: "MPearson@barrington220.org"),
            TeacherDataObject(name: "Brandon Pemberton", title: "Choir Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "BPemberton@barrington220.org"),
            TeacherDataObject(name: "Lauren Pennock", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "LPennock@barrington220.org"),
            TeacherDataObject(name: "Amalea Peters", title: "Teacher", subject: "Social Studies", email: "AMPeters@barrington220.org"),
            TeacherDataObject(name: "Andre Peters", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "AAPeters@barrington220.org"),
            TeacherDataObject(name: "Susan Podolski", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "SPodolski@barrington220.org"),
            TeacherDataObject(name: "Daniel Pohlman", title: "Teacher", subject: "Social Studies", email: "DPohlman@barrington220.org"),
            TeacherDataObject(name: "Stephanie Pohlman", title: "Teacher", subject: "Social Studies", email: "SPohlman@barrington220.org"),
            TeacherDataObject(name: "Mark Polzin", title: "Technology Support Supervisor", subject: "District Administrative Center, Technology & Innovation", email: "MDPolzin@barrington220.org"),
            TeacherDataObject(name: "Marie Popovich", title: "Academic Support Teacher", subject: "English", email: "MPopovich@barrington220.org"),
            TeacherDataObject(name: "Jennifer Poulos", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "JPoulos@barrington220.org"),
            TeacherDataObject(name: "Vicky Poznanski", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "VPoznanski@barrington220.org"),
            TeacherDataObject(name: "Kimberly Priola", title: "Administrative Assistant to Post High School Counselors", subject: "College Counseling", email: "KPriola@barrington220.org"),
            TeacherDataObject(name: "Moira Quealy", title: "Teacher", subject: "English", email: "MQuealy@barrington220.org"),
            TeacherDataObject(name: "Jennifer Quinlan", title: "Spanish Teacher", subject: "BHS World Language", email: "JRQuinlan@barrington220.org"),
            TeacherDataObject(name: "Crystal Quintana", title: "Administrative Support Specialist", subject: "Safety & Security", email: "CQuintana@barrington220.org"),
            TeacherDataObject(name: "Jaime Quintana", title: "Technology Support Technician", subject: "District Administrative Center, Technology & Innovation", email: "JQuintana1@barrington220.org"),
            TeacherDataObject(name: "Jaime Quintana", title: "Warehouse Clerk", subject: "Support Personnel", email: "JQuintana@barrington220.org"),
            TeacherDataObject(name: "Patricia Radke", title: "Student Wellness Coordinator", subject: "Wellness", email: "PRadke@barrington220.org"),
            TeacherDataObject(name: "Sam Raia", title: "Physical Education Teacher", subject: "Life Skills", email: "SRaia@barrington220.org"),
            TeacherDataObject(name: "Linda Ray", title: "Administrative Assistant to Athletic Director", subject: "BHS Athletics", email: "LRay@barrington220.org"),
            TeacherDataObject(name: "Paige Reconnu", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "PReconnu@barrington220.org"),
            TeacherDataObject(name: "Penelope Revis", title: "Teacher", subject: "Social Studies", email: "PRevis@barrington220.org"),
            TeacherDataObject(name: "Katelyn Reyes", title: "Dance Teacher", subject: "Life Skills, BHS Fine, Visual & Performing Arts", email: "KReyes@barrington220.org"),
            TeacherDataObject(name: "Kelley Rice", title: "Crisis Intervention Aide", subject: "BHS Student Services & Support", email: "KRice@barrington220.org"),
            TeacherDataObject(name: "Christopher Rierson", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "CRierson@barrington220.org"),
            TeacherDataObject(name: "Brigit Riordan", title: "Bilingual Assistant", subject: "Support Personnel", email: "BRiordan@barrington220.org"),
            TeacherDataObject(name: "Elizabeth Robbins", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "ERobbins@barrington220.org"),
            TeacherDataObject(name: "Jennifer Robinson", title: "Assistant Principal / Pathways Principal", subject: "BHS Main Office", email: "JYRobinson@barrington220.org"),
            TeacherDataObject(name: "Heidi Rockwell", title: "MTSS Coach", subject: "Social Studies , English", email: "HRockwell@barrington220.org"),
            TeacherDataObject(name: "Carlota Rodelo", title: "Psychologist", subject: "BHS Student Services & Support", email: "CRodelo@barrington220.org"),
            TeacherDataObject(name: "Eric Rodrigo", title: "Teacher", subject: "Mathematics", email: "ERodrigo@barrington220.org"),
            TeacherDataObject(name: "Beatriz Rodriguez", title: "Spanish Teacher", subject: "BHS World Language", email: "BERodriguez@barrington220.org"),
            TeacherDataObject(name: "Benjamin Rodriguez", title: "Assistant Principal/Coordinator of Career Pathways & Community Partnerships", subject: "Career & Technical Education, BHS Main Office", email: "BRodriguez@barrington220.org"),
            TeacherDataObject(name: "Orlando Rodriguez", title: "Skilled Maintenance Worker", subject: "Buildings & Grounds", email: "ORodriguez@barrington220.org"),
            TeacherDataObject(name: "Ian Roets", title: "Library Technology Assistant", subject: "BHS Library Media Services", email: "IRoets@barrington220.org"),
            TeacherDataObject(name: "Christopher Rohde", title: "Department Chair", subject: "Mathematics", email: "CRohde@barrington220.org"),
            TeacherDataObject(name: "William Rohner", title: "Teacher", subject: "English", email: "WRohner@barrington220.org"),
            TeacherDataObject(name: "John Roncone", title: "Department Chair", subject: "Social Studies", email: "Jroncone@barrington220.org"),
            TeacherDataObject(name: "Angelica Rooney", title: "Administrative Assistant", subject: "Mathematics", email: "ARooney@barrington220.org"),
            TeacherDataObject(name: "Ryan Rooney", title: "Night Custodial Supervisor", subject: "Buildings & Grounds", email: "RRooney@barrington220.org"),
            TeacherDataObject(name: "Kayla Ross", title: "Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "KRoss@barrington220.org"),
            TeacherDataObject(name: "Justine Rovin", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "JRovin@barrington220.org"),
            TeacherDataObject(name: "Jessica Royal", title: "Teacher", subject: "Science", email: "JRoyal@barrington220.org"),
            TeacherDataObject(name: "Ryan Rubenstein", title: "Athletic Director", subject: "BHS Athletics", email: "RRubenstein@barrington220.org"),
            TeacherDataObject(name: "Michael Ryan", title: "Campus Attendant", subject: "Support Personnel", email: "MRyan@barrington220.org"),
            TeacherDataObject(name: "Nancy Saldana", title: "ELL Spanish Bilingual Counselor", subject: "BHS Counseling", email: "NSaldana@barrington220.org"),
            TeacherDataObject(name: "Joe Sanchez", title: "Teacher", subject: "Social Studies", email: "jsanchez@barrington220.org"),
            TeacherDataObject(name: "Veronica Sanchez", title: "ELL & Spanish for Spanish Speakers Teacher", subject: "BHS World Language", email: "VSanchez@barrington220.org"),
            TeacherDataObject(name: "Wendy Sanchez", title: "Physical Education Teacher", subject: "Life Skills", email: "WSanchez@barrington220.org"),
            TeacherDataObject(name: "Jose Santamaria", title: "Multilingual Specialist", subject: "Social Studies", email: "JSantamaria@barrington220.org"),
            TeacherDataObject(name: "Nichole Satera", title: "Director of Facilities", subject: "District Administrative Center, Buildings & Grounds", email: "NSatera@barrington220.org"),
            TeacherDataObject(name: "Susan Savage", title: "504 Case Manager", subject: "BHS Student Services & Support", email: "SSavage@barrington220.org"),
            TeacherDataObject(name: "Giuliana Scardina", title: "Counselor", subject: "BHS Counseling", email: "GScardina@barrington220.org"),
            TeacherDataObject(name: "Russell Schellhase", title: "Lead Athletic Trainer", subject: "BHS Athletics", email: "RSchellhase@barrington220.org"),
            TeacherDataObject(name: "Gayle Schikman", title: "Special Education Teacher", subject: "Student Services & Support", email: "GSchikman@barrington220.org"),
            TeacherDataObject(name: "Katherine Schmitt", title: "Instructional Coach", subject: "Teaching & Learning", email: "KSchmitt@barrington220.org"),
            TeacherDataObject(name: "Lauren Schoepp", title: "Spanish Teacher", subject: "BHS World Language", email: "LSchoepp@barrington220.org"),
            TeacherDataObject(name: "Megan Scianna", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "MScianna@barrington220.org"),
            TeacherDataObject(name: "Mary Scotillo", title: "Teacher", subject: "Science", email: "MScotillo@barrington220.org"),
            TeacherDataObject(name: "Traci Segobiano", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "TSegobiano@barrington220.org"),
            TeacherDataObject(name: "Robert Seidel", title: "Teacher", subject: "Social Studies", email: "RSeidel@barrington220.org"),
            TeacherDataObject(name: "Allan Sekulic", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "ASekulic@barrington220.org"),
            TeacherDataObject(name: "Clark Sheldon", title: "Orchestra Teacher", subject: "BHS Fine, Visual & Performing Arts", email: "CSheldon@barrington220.org"),
            TeacherDataObject(name: "Melanie Silvestri", title: "Counselor", subject: "BHS Counseling", email: "MSilvestri@barrington220.org"),
            TeacherDataObject(name: "Damian Simmons", title: "Teacher", subject: "Science", email: "Dsimmons@barrington220.org"),
            TeacherDataObject(name: "Jeneen Smith-Underwood", title: "Student Services Assistant", subject: "BHS Student Services & Support", email: "JSmithUnderwood@barrington220.org"),
            TeacherDataObject(name: "Scott Snyder", title: "Driver's Education Teacher", subject: "Life Skills", email: "SSnyder@barrington220.org"),
            TeacherDataObject(name: "Michelle Solverson", title: "Student Services Assistant", subject: "Student Services & Support", email: "MSolverson@barrington220.org"),
            TeacherDataObject(name: "Thorwald Solverson", title: "Teacher", subject: "Mathematics", email: "TSolverson@barrington220.org"),
            TeacherDataObject(name: "Sheila Soss", title: "Spanish Teacher", subject: "BHS World Language", email: "SSoss@barrington220.org"),
            TeacherDataObject(name: "Hagop Soulakian", title: "Business INCubator Teacher", subject: "Career & Technical Education", email: "HSoulakian@barrington220.org"),
            TeacherDataObject(name: "Lindsey Spadavecchio", title: "Teacher", subject: "Mathematics", email: "LSpadavecchio@barrington220.org"),
            TeacherDataObject(name: "Christian Spandiary", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "CSpandiary@barrington220.org"),
            TeacherDataObject(name: "Dawn Spata", title: "Student Services Assistant", subject: "Student Services & Support", email: "DSpata@barrington220.org"),
            TeacherDataObject(name: "Barbara Spicer", title: "Administrative Assistant", subject: "English", email: "BSpicer@barrington220.org"),
            TeacherDataObject(name: "Stephanie Spiewak", title: "Assistant Principal / Coordinator of Secondary Counseling", subject: "BHS Main Office, BHS Counseling", email: "SSpiewak@barrington220.org"),
            TeacherDataObject(name: "Jennifer Steib", title: "Administrative Assistant", subject: "Life Skills", email: "JSteib@barrington220.org"),
            TeacherDataObject(name: "Scott Steib", title: "Health Teacher", subject: "Life Skills", email: "SSteib@barrington220.org"),
            TeacherDataObject(name: "Michelle Steiner", title: "Social Worker", subject: "BHS Student Services & Support", email: "MSteiner@barrington220.org"),
            TeacherDataObject(name: "Kelsey Strauch", title: "Foundations Program Teacher", subject: "BHS Student Services & Support", email: "kstrauch@barrington220.org"),
            TeacherDataObject(name: "Jayne Straumann", title: "Library Technology Assistant", subject: "BHS Library Media Services", email: "JStraumann@barrington220.org"),
            TeacherDataObject(name: "Brandon Stroh", title: "Assistant Department Chair", subject: "BHS Student Services & Support", email: "BStroh@barrington220.org"),
            TeacherDataObject(name: "Jennifer Stroh", title: "Post High School Counselor", subject: "College Counseling", email: "JDStroh@barrington220.org"),
            TeacherDataObject(name: "Melanie Stumpf", title: "Chinese Teacher", subject: "BHS World Language", email: "MStumpf@barrington220.org"),
            TeacherDataObject(name: "Jessica Surprenant", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "JSurprenant@barrington220.org"),
            TeacherDataObject(name: "Deborah Swiatek", title: "Administrative Assistant to Principal", subject: "BHS Main Office", email: "DSwiatek@barrington220.org"),
            TeacherDataObject(name: "Michael Szewczykowski", title: "Teacher", subject: "Mathematics", email: "MSzewczykowski@barrington220.org"),
            TeacherDataObject(name: "Henrique Talizin", title: "Campus Attendant", subject: "Support Personnel", email: "HTalizin@barrington220.org"),
            TeacherDataObject(name: "Erin Tantillo", title: "Environmental Science Teacher", subject: "Science, Career & Technical Education", email: "ETantillo@barrington220.org"),
            TeacherDataObject(name: "Jill Thennes", title: "Speech Clinician", subject: "BHS Student Services & Support", email: "JThennes@barrington220.org"),
            TeacherDataObject(name: "Kevin Thomas", title: "Grounds and Maintenance Foreman", subject: "Buildings & Grounds", email: "KDThomas@barrington220.org"),
            TeacherDataObject(name: "Brigid Tileston", title: "District Director of Fine, Visual & Performing Arts", subject: "Teaching & Learning, Fine, Visual & Performing Arts", email: "BTileston@barrington220.org"),
            TeacherDataObject(name: "Kiersten Tinkoff", title: "Counselor", subject: "BHS Counseling", email: "KTinkoff@barrington220.org"),
            TeacherDataObject(name: "Adrienne Tischauser", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "ATischauser@barrington220.org"),
            TeacherDataObject(name: "Ryan Trostrud", title: "Special Education Teacher", subject: "BHS Student Services & Support", email: "RTrostrud@barrington220.org"),
            TeacherDataObject(name: "Bryan Tucker", title: "Counselor", subject: "BHS Counseling", email: "BTucker@barrington220.org"),
            TeacherDataObject(name: "Laura Turngren", title: "Teacher", subject: "Science", email: "LTurngren@barrington220.org"),
            TeacherDataObject(name: "Steven Underwood", title: "Coordinator of Document Systems", subject: "Technology & Innovation", email: "SUnderwood@barrington220.org"),
            TeacherDataObject(name: "Angela Vallee-Larsen", title: "Spanish Teacher", subject: "BHS World Language", email: "AValleeLarsen@barrington220.org"),
            TeacherDataObject(name: "Pamela Van Leirsburg", title: "Teacher", subject: "Mathematics", email: "PVanLeirsburg@barrington220.org"),
            TeacherDataObject(name: "Michael Venezia", title: "Campus Attendant", subject: "Support Personnel", email: "MVenezia@barrington220.org"),
            TeacherDataObject(name: "Randal Walker", title: "Campus Attendant", subject: "Support Personnel", email: "RWalker@barrington220.org"),
            TeacherDataObject(name: "Jennifer Walsh", title: "Teacher Librarian", subject: "BHS Library Media Services", email: "JYWalsh@barrington220.org"),
            TeacherDataObject(name: "Randi Walters", title: "Administrative Assistant", subject: "Science", email: "RWalters@barrington220.org"),
            TeacherDataObject(name: "Amy Wasil", title: "German Teacher", subject: "BHS World Language", email: "AWasil@barrington220.org"),
            TeacherDataObject(name: "Anthony Wass", title: "Teacher", subject: "English", email: "TWass@barrington220.org"),
            TeacherDataObject(name: "Cary Waxler", title: "Teacher", subject: "Social Studies", email: "CWaxler@barrington220.org"),
            TeacherDataObject(name: "Jessica Wayne", title: "Special Education Teacher", subject: "Student Services & Support", email: "JWayne@barrington220.org"),
            TeacherDataObject(name: "Kurt Weisenburger", title: "Teacher", subject: "Social Studies", email: "KWeisenburger@barrington220.org"),
            TeacherDataObject(name: "Haley Wickstrom", title: "Teacher", subject: "Social Studies", email: "HWickstrom@barrington220.org"),
            TeacherDataObject(name: "Teresa Wiesen", title: "Substitute Coordinator", subject: "Support Personnel", email: "TWiesen@barrington220.org"),
            TeacherDataObject(name: "Amy Winkelman", title: "Prevention and Wellness Program Coordinator", subject: "Wellness", email: "AWinkelman@barrington220.org"),
            TeacherDataObject(name: "Patrick Wire", title: "Teacher", subject: "Social Studies", email: "PWire@barrington220.org"),
            TeacherDataObject(name: "Kathryn Wolfkiel", title: "Department Chair", subject: "BHS World Language", email: "KWolfkiel@barrington220.org"),
            TeacherDataObject(name: "Yang Yang", title: "Chinese Teacher", subject: "BHS World Language", email: "YYang@barrington220.org"),
            TeacherDataObject(name: "Nicholas Yeager", title: "Academic Support Teacher", subject: "BHS Counseling", email: "NYeager@barrington220.org"),
            TeacherDataObject(name: "Christopher Ytzen", title: "PLTW/Engineering Teacher", subject: "Science, Career & Technical Education", email: "CYtzen@barrington220.org"),
            TeacherDataObject(name: "Colleen Zenner", title: "Teacher", subject: "Science", email: "CZenner@barrington220.org"),
            TeacherDataObject(name: "Joseph Zimka", title: "Graphic Design & Digital Arts Teacher", subject: "Career & Technical Education, BHS Fine, Visual & Performing Arts", email: "JZimka@barrington220.org"),
        ]
    }
}
